config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  resources :projects do
     resources :items
  end
  
  resources :users
 

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  # Uses 'internal' in invite routes to distinguish from 'external' invites to
  # people who do not have an account with the app yet.
  post   'internal_invite' => 'invitations#create'
  delete 'cancel_invite' => 'invitations#cancel'
  post   'accept_internal_invite' => 'participates#create'
  delete 'decline_invite' => 'invitations#decline'
  get "register" => "users#new"
  get "/projects/:project_id/items/:id/new" => "items#new_child", as: :new_child
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<% if current_user %>
  <div class="row">
    <div class="col-md-4">
      <h1>Your Projects</h1>
      <%= render partial: 'projects/user_index', 
                          locals: { projects: current_user.all_projects } %>
      <%= link_to 'Create Project', new_project_path, class: "btn btn-primary" %>
    </div>
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <% if current_user.has_received_invitations? %>
        <%= render 'invitations/received_invitations' %>
      <% end %>
      <% if current_user.has_given_invitations? %>
        <%= render 'invitations/given_invitations' %>
      <% end %>
    </div>    
  </div>
<% else %>
  <h1>Welcome to ArchiveSQuirreL</h1>
<% end %>