config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  resources :projects do
     resources :items
  end
  
  resources :users
 

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  # Uses 'internal' in invite routes to distinguish from 'external' invites to
  # people who do not have an account with the app yet.
  post   'internal_invite' => 'invitations#create'
  delete 'cancel_invite' => 'invitations#cancel'
  post   'accept_internal_invite' => 'participates#create'
  delete 'decline_invite' => 'invitations#decline'
  get "register" => "users#new"
  get "/projects/:project_id/items/:id/new" => "items#new_child", as: :new_child
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base

  belongs_to :invitee, :class_name => "User"
  belongs_to :inviter, :class_name => "User"
  belongs_to :project
  
  validate :no_existing_invitation
  validate :not_existing_member
  
  def main_error
    #string for error for error notice
  end
  
  def has_been_accepted
    self.destroy
  end
  
  private
  
  def not_existing_member
    membership = self.invitee.is_member_of_project?(self.project)
    errors.add(:existing_member, "This user is already a member of the project.") if membership
  end
  
  def no_existing_invitation
    invitation = self.invitee.is_invited_to_project?(self.project)
    errors.add(:existing_invite, "This user has already been invited to the project.") if invitation
  end
  
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  
  before_action :require_login
  
  def create
    project = get_authorized_project(params[:project]); return if performed?
    invitee = get_valid_user(params[:invitee_name]); return if performed?
    @invitation = Invitation.new(inviter: current_user, 
                                 invitee: invitee,
                                 project: project)
    if @invitation.save
      redirect_to project, notice: "Invitation sent to #{params[:invitee_name]}!"
    else
      redirect_to :back, notice: "Invitation invalid: #{@invitation.errors.first[1]}"
    end      
  end
  
  def decline
    invite = current_user.received_invitations.find(params[:invite_id])
    invite.destroy
    redirect_to :back, notice: "The invitation has been deleted."
  end
  
  def cancel
    invite = current_user.given_invitations.find(params[:invite_id])
    invite.destroy
    redirect_to :back, notice: "The invitation has been cancelled."
  end
  
  private
  
  def get_authorized_project(project_id)
    project = Project.find_by(id: project_id)
    return project if current_user.is_member_of_project?(project)
    redirect_to root_path and return false  
  end
  
  def get_valid_user(login_or_email)
    if user = find_user_by_login_or_email(login_or_email)
      return user
    else
      # Change behaviour once external invitations are implemented.
      redirect_to :back, notice: "#{login_or_email} is an invalid user."
    end
  end
  
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= form_tag internal_invite_path, class: "form-inline" do %>
  <fieldset>
    <div class="form-group">
      <%= text_field_tag :invitee_name, nil, class: "form-control" %>
      <%= hidden_field_tag :project, project_id %>
      <%= submit_tag 'Invite', class: "btn btn-success" %>
    </div>
  </fieldset>
<% end %>

app/views/invitations/_given_invitations.html.erb
<h4>Invitations You Have Given</h4>
  <table class="table table-hover">
    <% current_user.given_invitations.each do |invite| %>
       <tr><td>
       You have invited <%= formatted_user_profile_link invite.invitee %>
        to <%= link_to invite.project.name, project_path(invite.project) %>.
        <p><%= button_to 'Cancel Invitation', cancel_invite_path,
                                 method: :delete,
                                 params: { invite_id: invite.id },
                                 class: "btn btn-danger btn-xs" %></p>
      </td></tr>
    <% end %>
  </table>

app/views/invitations/_received_invitations.html.erb
<h4>Pending Invitations</h4>
    <table class="table table-hover">
      <% current_user.received_invitations.each do |invite| %>
        <tr><td>
            <%= formatted_user_profile_link invite.inviter %>
            has invited you to the project
            <%= link_to invite.project.name, project_path(invite.project) %>.
            <p>
              <div class="notification-button">
                <%= button_to 'Accept', accept_internal_invite_path, 
                                        params: { invite_id: invite.id },
                                        class: "btn btn-success btn-sm" %>
              </div>
              <div class="notification-button">
                <%= button_to 'Decline', decline_invite_path,
                                         method: :delete,
                                         params: { invite_id: invite.id }, 
                                         class: "btn btn-danger btn-sm" %>
              </div>
              <div style="clear:both">
              </div>
            </p>
          </td></tr>
      <% end %>
    </table>