config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  resources :projects do
     resources :items
  end
  
  resources :users
 

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  # Uses 'internal' in invite routes to distinguish from 'external' invites to
  # people who do not have an account with the app yet.
  post   'internal_invite' => 'invitations#create'
  delete 'cancel_invite' => 'invitations#cancel'
  post   'accept_internal_invite' => 'participates#create'
  delete 'decline_invite' => 'invitations#decline'
  get "register" => "users#new"
  get "/projects/:project_id/items/:id/new" => "items#new_child", as: :new_child
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :project
  validates :project, presence: true
  belongs_to :user
  validates :user, presence: true
  
  has_many :item_relationships, dependent: :destroy
  
  has_many :parent_relationships, foreign_key: :child_id, class_name: "ItemRelationship"
  has_many :parents, through: :parent_relationships, source: :parent
  
  has_many :child_relationships, foreign_key: :parent_id, class_name: "ItemRelationship"
  has_many :children, through: :child_relationships, source: :child
  
  has_many :top_level_relationships, dependent: :destroy
  has_many :parent_projects, through: :top_level_relationships, source: :project
  
  def deletable_by?(user)
    self.creator?(user) || self.admin?(user)
  end
  
  def creator?(user)
    self.user == user
  end
  
  def admin?(user)
    self.project.project_admin?(user)
  end
  
  def top_level?
    self.top_level_relationships.any?
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  # This before filter also defines @project for the use of each method.
  before_action :require_project_member
  
  def show
    @item = Item.find(params[:id])
  end
  
  def new
    @item = @project.items.new
  end
  
  def new_child
    @parent = Item.find(params[:id])
    @item = @project.items.new
    render :new
  end
  
  def create
    
    # This looks very messy and should be cleaned up, but right now I just
    # want my tests to pass.
    
    @item = @project.items.new(item_params)
    @item.project = @project
    @item.user = current_user
    @parent = @project.items.find_by(id: params[:parent]) if params[:parent]
    if @item.save
      if @parent
        ItemRelationship.create!(parent: @parent, child: @item) 
      else
        TopLevelRelationship.create!(project: @project, 
                                     item: @item, 
                                     relationship: params[:top_level])
      end
      redirect_to project_item_path(@project, @item),
                 notice: "Item successfully added!"
    else
      render :new
    end 
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to project_item_path(@project, @item), notice: "Changes saved."
    else
      render :edit
    end
  end
  
  def destroy
    @item = Item.find(params[:id])
    if @item.deletable_by?(current_user)
      @item.destroy
      redirect_to project_path(@project)
    else
      redirect_to :back, notice: "You are not authorized to do this."
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :description, :level)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for([@project, @item], class: "form-inline") do |f| %>
  <%= render 'shared/errors', object: @item %>
  <fieldset>
      <div class="form-group">
        <%= f.label "Name/Title" %><br/>
        <%= f.text_field :name, size: 40, autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.label "Description" %><br/>
        <%= f.text_area :description, cols: 40, rows: 7 %>
      </div>
      <div class="form-group">
        <%= f.label "Level" %><br/>
        <%= f.text_field :level, size: 40, value: "Item" %>
      </div>
    <%= hidden_field_tag :project, @project.id %>
    <% if @parent %>
      <%= hidden_field_tag :parent, @parent.id %>
    <% else %>
      <%= hidden_field_tag :top_level, "default" %>
    <% end %>
    <p>
      <% if @item.new_record? && @parent %>
        <%= f.submit "Add Item", class: "btn btn-success" %>
      <% elsif @item.new_record? %>
        <%= f.submit "Create Item" %>
      <% else %>
        <%= f.submit 'Save Changes', class: "btn btn-primary" %>
      <% end %>
      <%= link_to 'Cancel', @project, class: "btn btn-danger" %>
    </p>
  </fieldset>

<% end %>

app/views/items/edit.html.erb
<h1>Edit <%= @item.name %></h1>
<%= render 'form' %>

app/views/items/new.html.erb
<% if @parent %>
  <h1>Add a New Item to <%= @parent.name %></h1>
<% else %>
  <h1>Add an Item</h1>
<% end %>
<%= render 'form' %>

app/views/items/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h5><%= link_to @project.name, project_path(@project) %></h5>
    <h1 class="item-title">
    <% if @item.level.blank? %>
      <%= "#{@item.name}" %>
    <% else %>
      <%= "#{@item.level.titleize}: #{@item.name}" %>
    <% end %>
    </h1>
  </div>
</div>

<div class="row">
  
  <div class="col-md-2">
    <% if @item.parents.any? %>
      <h5>Belongs to</h5>
        <% @item.parents.each do |parent| %>
          <p><%= link_to parent.name, project_item_path(@project, parent) %></p>
        <% end %>
    <% end %>
  </div>
  
  <div class="col-md-10">
    
    <div class="row">
      <div class="col-md-12">
        <h5>Description</h5>
        <p><%= @item.description %></p>
          <% if @project.project_member?(current_user) %>
          <p><%= link_to 'Edit', edit_project_item_path(@item.project, @item),
                                 class: "btn btn-default" %></p>
          <% end %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-12">
        <% if @item.children.any? %>
          <h4>Contains</h4>
            <ul>
            <% @item.children.each do |child| %>
              <li><%= link_to child.name, project_item_path(@project, child) %></li>
            <% end %>
            </ul>
        <% end %>
        <% if @project.project_member?(current_user) %>
          <%= link_to 'Add Item', new_child_path(@item.project, @item), 
                                  class: "btn btn-default" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">


    <p>Added by <%= formatted_user_profile_link(@item.user) %>.</p>
    <p><% if @item.deletable_by? (current_user) %>
      <%= link_to 'Delete', project_item_path(@project, @item), 
                            method: :delete,
                            data: { confirm: "Are you sure?" },
                            class: "btn btn-xs btn-danger" %></p>
    <% end %>
  </div>
</div>