config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  resources :projects do
     resources :items
  end
  
  resources :users
 

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  # Uses 'internal' in invite routes to distinguish from 'external' invites to
  # people who do not have an account with the app yet.
  post   'internal_invite' => 'invitations#create'
  delete 'cancel_invite' => 'invitations#cancel'
  post   'accept_internal_invite' => 'participates#create'
  delete 'decline_invite' => 'invitations#decline'
  get "register" => "users#new"
  get "/projects/:project_id/items/:id/new" => "items#new_child", as: :new_child
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Archivesquirrel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>    
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'ArchiveSQuirreL', root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= name_displayed_for current_user %> (logged in) <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#"><%= link_to 'Profile', user_path(current_user) %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
                </ul>
              </li>            
            <% else %>
              <li><%= link_to 'Register', register_path %></li>
              <li><%= link_to 'Log In', login_path %></li>
            <% end %>
            
          </ul>
        </div>
      </div>
    </nav>
</header>
<div class="container">
    <%= render 'layouts/flashes' %>
    <%= yield %>
</div>

</body>
</html>